[tool.poetry]
name = "goit-dsml-hw-01"
version = "0.1.0"
description = ""
authors = ["moolvi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiosqlite = "^0.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
